server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.127:3306/life_circle?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

  data:
    redis:
      host: 192.168.100.127
      port: 6379
      password:
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.slim.blogbackend.entity
  configuration:
    map-underscore-to-camel-case: true


